version: "3.7"

services:
  database:
    image: library/postgres:13.0-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

  php-fpm:
    image: webdevops/php-dev:7.4-alpine
    volumes:
      - ".:/app"
    working_dir: "/app"
    depends_on:
      - database
    links:
      - database

  nginx:
    image: webdevops/nginx
    ports:
      - 8080:80
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      WEB_PHP_SOCKET: php-fpm:9000
    volumes:
      - ".:/app"
    depends_on:
      - php-fpm

volumes:
  pgdata: